# Generated by Django 4.1.5 on 2023-02-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_options_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
