# Generated by Django 4.1.5 on 2023-02-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
