# Generated by Django 4.1.5 on 2023-02-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(related_name='custom_group_name', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='custom_permission_name', to='auth.permission')),
            ],
        ),
    ]
